spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: user_java
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8010