spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service-products
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            AuthFilter

        - id: warehouses-service-warehouses
          uri: lb:http://WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/warehouses/**
          filters:
            AuthFilter

        - id: warehouses-service-transfers
          uri: lb:http://WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/transfers/**
          filters:
            AuthFilter

        - id: product-service-categories
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
          filters:
            AuthFilter

        - id: product-service-categories
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            AuthFilter

server:
  port: 8222