spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service-products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: AuthFilter

        - id: warehouses-service-warehouses
          uri: lb://WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/warehouses/**
          filters:
            - name: AuthFilter

        - id: warehouses-service-transfers
          uri: lb://WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/transfers/**
          filters:
            - name: AuthFilter

        - id: product-service-categories
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - name: AuthFilter

        - id: customer-service-customers
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - name: AuthFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: AuthFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: AuthFilter

server:
  port: 8222
