spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

app:
  security:
    jwt: MT6RD/GBconH31eRBmDUpe4pIXDen/5VmHfSpU69ZbfzLpvvWXcPFBpiMRRW4Cib