spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service


application:
  security:
    jwt: MT6RD/GBconH31eRBmDUpe4pIXDen/5VmHfSpU69ZbfzLpvvWXcPFBpiMRRW4Cib
    #    in days
    expiration: 1
    activationTokenLen: 6
    tokenExpirationTime: 15